development:
  adapter: postgresql
  encoding: utf8
  database: ideas_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ideas_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ideas_production
  pool: 5
  username: 
  password: